### ISSUE TITLE
Need update dependencies

### ISSUE THREAD

**Issue by ivanzhadnov** [bluefireteam/daylight#13]
Because daylight 2.0.0 depends on intl ^0.17.0 and no versions of daylight match >2.0.0 <3.0.0, daylight ^2.0.0 requires intl ^0.17.0.
So, because XXX depends on both intl ^0.18.0 and daylight ^2.0.0, version solving failed.

**Comment by RaphaelArabeyre** [comment]
duplicat https://github.com/bluefireteam/daylight/issues/12#issuecomment-1637972834
