### ISSUE TITLE
Results offset when using a DateTime that is utc as input

### ISSUE THREAD

**Issue by christophbschwarz** [bluefireteam/daylight#5]
When using `calculateEvent` or `calculateForDay` of the `DaylightCalculator` and using an input `DateTime` which already is UTC, the results are offset from the correct time by the difference between local and utc.

You should be able to easily reproduce this problem by using, e.g. `final todayUtc = DateTime.utc(2020, 1, 19)` as the input.

**Comment by laminr** [comment]
I got the same problem, while I need to get calculation at position which is not specifically the same as the phone timezone...
Any news about it?

**Comment by renancaraujo** [comment]
Added a fix for this on #20
